name: study_ai
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.1.2
  file_picker: ^5.3.0
  flutter:
    sdk: flutter
  flutter_image_stack: ^0.0.6
  google_fonts: ^4.0.4
  http: ^0.13.6
  image_picker: ^0.8.7+5
  logger: ^1.3.0
  provider: ^6.0.5
  responsive_sizer: ^3.1.1
  social_login_buttons: ^1.0.7
  step_progress_indicator: ^1.0.2
  supabase_auth_ui: ^0.1.0+2
  supabase_flutter: ^1.9.2
  url_launcher: ^6.1.11
  dotted_border: ^2.0.0+3
  typewritertext: ^1.8.0
  flip_card: ^0.7.0
  page_view_dot_indicator: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
